version: '3.8'

services:
  expense-tracker:
    image: expense-tracker:latest
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: expense-tracker
    depends_on:
      - db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Optional: Initialize the database with SQL scripts from the host
    # volumes:
    #   - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data: