spring:

  application:
    name: Expenses-Tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    cors:
      allowed-origins: "*"

server:
  port: 8080

management:
  logging:
    export:
      enabled: on
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
      # include: health,info # Or just enable specific ones
  server:
    port: 8081